CREATE DATABASE ECLASSIMOVEL;
USE ECLASSIMOVEL;

CREATE TABLE CEP(
CEP 		INT PRIMARY KEY,
ENDERECO        VARCHAR(255),
BAIRRO		VARCHAR(100),
CIDADE		VARCHAR(60),
ESTADO		CHAR(2)
);

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY,
ID_TIPO INT,-- 01-PJ, 02-PF
CPF INT NULL,
NOME VARCHAR(50),
EMAIL VARCHAR(50),
TEL VARCHAR(15),
CEP INT,
NUM_RESI INT,
COMPLEMENTO VARCHAR(30)
);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_ID_TIPO FOREIGN KEY(ID_TIPO) REFERENCES TIPO_CLIENTE(ID_TIPO);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CEP FOREIGN KEY(CEP) REFERENCES CEP(CEP);

CREATE TABLE TIPO1_IMOVEL(
ID_TIPO1 	INT PRIMARY KEY,
DESCRI		VARCHAR(50)
);

CREATE TABLE TIPO2_IMOVEL(
ID_TIPO2	INT PRIMARY KEY,
DESCRI		VARCHAR(50)
);

CREATE TABLE IMOVEL(
ID_IMOVEL 		INT PRIMARY KEY,
ID_CLIENTE		INT,
ID_TIPO1		INT,
ID_TIPO2		INT,
TAMANHO			FLOAT,
QTD_QUARTOS		INT,
QTD_BANHEIRO	INT,
CEP				INT,
NUMERO			INT,
COMP			VARCHAR(50),
INFO			TEXT
);
ALTER TABLE IMOVEL ADD CONSTRAINT FK_ID_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE IMOVEL ADD CONSTRAINT FK_ID_TIPO1 FOREIGN KEY(ID_TIPO1) REFERENCES TIPO1_IMOVEL(ID_TIPO1);
ALTER TABLE IMOVEL ADD CONSTRAINT FK_ID_TIPO2 FOREIGN KEY(ID_TIPO2) REFERENCES TIPO2_IMOVEL(ID_TIPO2);
ALTER TABLE IMOVEL ADD CONSTRAINT FK_CEP1 FOREIGN KEY(CEP) REFERENCES CEP(CEP);

CREATE TABLE ANUNCIO(
ID_ANUNCIO 	INT PRIMARY KEY,
ID_CLIENTE 	INT,
ID_IMOVEL 	INT,
TITULO 		VARCHAR(50),
MEMO		TEXT
);	
ALTER TABLE ANUNCIO ADD CONSTRAINT FK_ID_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE ANUNCIO ADD CONSTRAINT FK_ID_CLIENTE FOREIGN KEY(ID_IMOVEL) REFERENCES IMOVEL(ID_IMOVEL);

